### ISSUE TITLE
Project info UI enhancements

### ISSUE THREAD

**Issue by madsrh** [canonical/lxd-toolbox#276]
I just saw this info UI PR and was wondering about the color. I don't believe adding color to the "title" nor the expansion arrow is normal practice. I would keep everything monochrome, add a divider/line below the expansion panel and add a bit padding around the content.

Just my 2 cent 😄

![image](https://user-images.githubusercontent.com/3986894/205766186-ea325524-f1e7-4361-a5b0-ab458233cecc.png)

![mockup](https://user-images.githubusercontent.com/3986894/205766079-3ae7e427-a3c1-43f6-a03d-56e64927643e.gif)

**Comment by jpnurmi** [comment]
I'm not familiar with them but `YaruExpansionLPanelList` and `YaruExpandable` could be worth trying :)
